/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author asuss
 */
public class FormKonversi extends javax.swing.JFrame {

    /**
     * Creates new form FormKonversi
     */
    public FormKonversi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupArah = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblInput = new javax.swing.JLabel();
        txtInput = new java.awt.TextField();
        lblSkala = new javax.swing.JLabel();
        comboSkala = new javax.swing.JComboBox<>();
        lblArah = new javax.swing.JLabel();
        rbtnKeCelcius = new javax.swing.JRadioButton();
        rbtnDariCelcius = new javax.swing.JRadioButton();
        btnKonversi = new javax.swing.JButton();
        lblHasil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudul.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblJudul.setText("APLIKASI KONVERSI SUHU");
        jPanel1.add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        lblInput.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblInput.setText("Masukkan Nilai Suhu :");
        jPanel1.add(lblInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtInput.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInputKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputKeyTyped(evt);
            }
        });
        jPanel1.add(txtInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 80, -1));

        lblSkala.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblSkala.setText("Skala Asal                  :");
        jPanel1.add(lblSkala, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 120, -1));

        comboSkala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));
        jPanel1.add(comboSkala, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        lblArah.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblArah.setText("Arah Konversi");
        jPanel1.add(lblArah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        groupArah.add(rbtnKeCelcius);
        rbtnKeCelcius.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        rbtnKeCelcius.setText("Dari Skala Asal Ke Celcius");
        rbtnKeCelcius.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnKeCelciusItemStateChanged(evt);
            }
        });
        jPanel1.add(rbtnKeCelcius, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        groupArah.add(rbtnDariCelcius);
        rbtnDariCelcius.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        rbtnDariCelcius.setText("Dari Celcius Ke Arah Tujuan");
        rbtnDariCelcius.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnDariCelciusItemStateChanged(evt);
            }
        });
        jPanel1.add(rbtnDariCelcius, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, 20));

        btnKonversi.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnKonversi.setText("KONVERSI");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });
        jPanel1.add(btnKonversi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        lblHasil.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblHasil.setText("Hasil Konversi");
        jPanel1.add(lblHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
try {
        double input = Double.parseDouble(txtInput.getText());
        String skala = comboSkala.getSelectedItem().toString();
        double hasil = 0;

        if (rbtnDariCelcius.isSelected()) {
            if (skala.equals("Fahrenheit")) hasil = celciusToFahrenheit(input);
            else if (skala.equals("Reamur")) hasil = celciusToFahrenheit(reamurToCelcius(input));
            else if (skala.equals("Kelvin")) hasil = celciusToFahrenheit(kelvinToCelcius(input));
        } 
        else if (rbtnKeCelcius.isSelected()) {
            if (skala.equals("Fahrenheit")) hasil = fahrenheitToCelcius(input);
            else if (skala.equals("Reamur")) hasil = reamurToCelcius(input);
            else if (skala.equals("Kelvin")) hasil = kelvinToCelcius(input);
        }

        lblHasil.setText(String.format("Hasil: %.2f", hasil));
    } catch (NumberFormatException e) {
        lblHasil.setText("Input tidak valid");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void txtInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyTyped
   char c = evt.getKeyChar();
    if (!Character.isDigit(c) && c != '.' && c != '-') {
        evt.consume();  // Batasi hanya angka dan titik
    }        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputKeyTyped

    private void rbtnKeCelciusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnKeCelciusItemStateChanged
  lblHasil.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnKeCelciusItemStateChanged

    private void rbtnDariCelciusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnDariCelciusItemStateChanged
  lblHasil.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDariCelciusItemStateChanged

    private void txtInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyReleased
   btnKonversiActionPerformed(null);        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKonversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKonversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKonversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKonversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKonversi().setVisible(true);
            }
        });
    }
    
private double celciusToFahrenheit(double c) {
    return (c * 9/5) + 32;
}

private double fahrenheitToCelcius(double f) {
    return (f - 32) * 5/9;
}

private double celciusToReamur(double c) {
    return c * 4/5;
}

private double reamurToCelcius(double r) {
    return r * 5/4;
}

private double celciusToKelvin(double c) {
    return c + 273.15;
}

private double kelvinToCelcius(double k) {
    return k - 273.15;
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonversi;
    private javax.swing.JComboBox<String> comboSkala;
    private javax.swing.ButtonGroup groupArah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblArah;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblInput;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblSkala;
    private javax.swing.JRadioButton rbtnDariCelcius;
    private javax.swing.JRadioButton rbtnKeCelcius;
    private java.awt.TextField txtInput;
    // End of variables declaration//GEN-END:variables
}
